services:
  - type: web
    name: qr-studio-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      gunicorn app.main:app -w 2 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT
    healthCheckPath: /health
    envVars:
      - key: ENV
        value: production
      - key: REDIS_URL
        fromService:
          type: redis
          name: qr-studio-redis
          property: connectionString
      - key: CORS_ORIGINS
        value: https://yourusername.github.io
      - key: MAX_FILE_SIZE
        value: "5242880"
      - key: RATE_LIMIT_REQUESTS
        value: "100"
      - key: RATE_LIMIT_WINDOW
        value: "3600"
      # Abuse Protection Settings
      - key: ENABLE_ABUSE_PROTECTION
        value: "true"
      - key: DAILY_QR_LIMIT
        value: "500"
      - key: HOURLY_QR_LIMIT
        value: "50"
      - key: DAILY_API_LIMIT
        value: "5000"
      - key: HOURLY_API_LIMIT
        value: "500"
      - key: MAX_CONCURRENT_REQUESTS
        value: "3"
      - key: BURST_REQUEST_THRESHOLD
        value: "15"
      - key: ERROR_RATE_THRESHOLD
        value: "0.6"
      - key: FIRST_BLOCK_DURATION
        value: "300"
      - key: SECOND_BLOCK_DURATION
        value: "900"
      - key: THIRD_BLOCK_DURATION
        value: "3600"
      - key: ADMIN_TOKEN
        fromSecret: ADMIN_TOKEN
      - key: SECRET_KEY
        fromSecret: SECRET_KEY

  - type: redis
    name: qr-studio-redis
    region: oregon
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []
